twig:
    file_name_pattern: '*.twig'
    globals:
        APPNAME: '%app.name%'
        NAVITEMS: '%app.navItems%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
